version: '3.8'  # Версия схемы Compose

services:
  mongo:
    image: mongo:latest
    container_name: top-apy-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: top-api
    ports:
      - "27018:27017"
    volumes:
      - top_api_mongo_data:/data/db
    command: mongod --wiredTigerCacheSizeGB 1.5

volumes:
  top_api_mongo_data: